server {
	
	listen 443 ssl;
	listen [::]:443 ssl; # opening connection from ipv4 address and ipv6 in port 443

	server_name ilarhrib.42.fr; # our host name so nginx know which website the request is for
	
	ssl_certificate /etc/nginx/ssl/inception.crt; # ngin need to know the ssl certs and key to check and decrypt the traffic 
	ssl_certificate_key /etc/nginx/ssl/inception.key; 
	ssl_protocols TLSv1.2 TLSv1.3; # using modern tls rather than the old vulnerable ones

	root /var/www/wordpress; # the root dir to search for the file requested if none is requested nginx search from left to right in the files we passed as default 
	index index.php index.html index.htm; 

	location / { # static file routing if it doeasnt find the filenname it search ofr a dir with that name if not throw an 404 not found error
		try_files $uri $uri/ =404;
	}

	location ~ \.php$ { # if the file requested end with .php we deliver it to Fastcgi to format it to html and pass it to wordpress
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
	}
}