[www] # specifing that this config is for this web pool "www"
user = www-data # stripping power from the php exec engine 
group = www-data
listen = 0.0.0.0:9000 # opening a door for ngnix requests
listen.owner = www-data transfering the ownership of the port to the standard user www-data
listen.group = www-data
pm = dynamic # making the process managment spawn children dynamicly
pm.max_children = 5 # max spawn 5 childs
pm.start_servers = 2 # where the container is up spawn 2 children 
pm.min_spare_servers = 1 # if no traffic is flowing keep 1 child up 
pm.max_spare_servers = 3 # if there was traffic and it began to dies leave 3 childs up
clear_env = no # stop the PHP-FPM from clearing the env for sercurity purposes
